In [1]:
"""Prog1 with 3 i/p features and no hidden layers"""

In [ ]:
import torch

In [4]:
def activation(x):
    """Sigmoid activation function(for o/p to be probability)....Arguments : x = torch.Tensor"""
    return 1/(1+torch.exp(-x))

In [6]:
"""Generate some data"""
torch.manual_seed(7) #Set the random seed so that things are predictable

"""Features are 5 random normal variables"""
features=torch.randn((1,5)) #2d tensor of 1 row nd 5 columns

"""True weights for our data, random normal variables again"""
weights = torch.randn_like(features)

"""and a true bias term"""
bias=torch.randn((1,1))

In [10]:
"""Solution"""

#making labels from data and weights

y=activation(torch.sum(features*weights)+bias)
print(y)
#OR
y=activation((features*weights).sum()+bias)
print(y)

tensor([[0.1595]])
tensor([[0.1595]])


In [16]:
#torch.mm(features,weights) #error bcz order of weights nd features is 1*5. we need to transpose weights
y=activation(torch.mm(features,weights.view(5,1)) + bias) #more efficient than torch.sum()
print(y)

tensor([[0.1595]])


In [28]:
"""Prog2 with 1 hidden layer with 2 items in it...3 i/p features and 1 o/p"""
import torch
torch.manual_seed(7)
features=torch.randn((1,3))

def activation(x):
    """Sigmoid activation function(for o/p to be probability)....Arguments : x = torch.Tensor"""
    return 1/(1+torch.exp(-x))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn((n_input, n_hidden))
# Weights for hidden layer to output layer
W2 = torch.randn((n_hidden, n_output))

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

"""print(features)
print(W1)
print(W2)
print(B1)
print(B2)"""
#output
#hidden layer values
h=activation(torch.mm(features, W1) + B1)
y=activation(torch.mm(h, W2) + B2)
print(y)


tensor([[-0.1468,  0.7861,  0.9468]])
tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])
tensor([[-1.6822],
        [ 0.3177]])
tensor([[0.1328, 0.1373]])
tensor([[0.2405]])
tensor([[0.3171]])


In [25]:
"""Numpy to torch nd vice versa"""
import numpy as np

#random array
a=np.random.rand(4,3)
print(a)

#torch tensor from array
b=torch.from_numpy(a)
print(b)

#tensor to numpy array
b.numpy()

"""Memory is shared between array nd tensor...any inplace operation changing value in any1 will reflect in the other as well"""

#Modifying tensor
print(b.mul_(2))
#Values in array also change
print(a)




[[0.31032805 0.32680047 0.98567641]
 [0.95156243 0.85335541 0.50641539]
 [0.82482037 0.53984041 0.85059938]
 [0.48317152 0.25027781 0.83568966]]
tensor([[0.3103, 0.3268, 0.9857],
        [0.9516, 0.8534, 0.5064],
        [0.8248, 0.5398, 0.8506],
        [0.4832, 0.2503, 0.8357]], dtype=torch.float64)
tensor([[0.6207, 0.6536, 1.9714],
        [1.9031, 1.7067, 1.0128],
        [1.6496, 1.0797, 1.7012],
        [0.9663, 0.5006, 1.6714]], dtype=torch.float64)
[[0.6206561  0.65360095 1.97135283]
 [1.90312486 1.70671081 1.01283078]
 [1.64964073 1.07968082 1.70119877]
 [0.96634303 0.50055562 1.67137931]]
