In [11]:
import torch

#the number of entries in the db
num_entries = 5000

db = torch.rand(num_entries) > 0.5
print(db)
print(db.shape)

tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8)
torch.Size([5000])


In [2]:
#GENERATE PARALLEL DATABASE WITH ONE ENTRY MISSING....5000 DBS WITH 4999 ENTRIES EACH

In [6]:
#HARDCODED EXAMPLE
'''remove_index = 2
torch.cat((db[0:2], db[3:]))''' #using slicing operation to remove the element at index 2

tensor([0, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8)

In [7]:
#FUNCTION TO CREATE PARALLEL DB
def get_parallel_db(db, remove_index):
    return torch.cat((db[0:remove_index], db[remove_index+1:]))
#get_parallel_db(db, 2).shape #verification

In [12]:
parallel_dbs = list()

In [13]:
for i in range(len(db)):
    pdb = get_parallel_db(db, i)
    parallel_dbs.append(pdb)

In [14]:
print(len(parallel_dbs)) #num of parallel dbs

5000


In [15]:
#PACKING THE ABOVE CODE INTO A FUNCTION
def get_parallel_dbs(db):
    parallel_dbs = list()
    
    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
    
    return parallel_dbs

In [16]:
pdbs = get_parallel_dbs(db)

In [17]:
pdbs

[tensor([1, 0, 1,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 1,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0

In [ ]:
#THEREFORE :D
def create_db_and_parallels(num_entries):
    db = torch.rand(num_entries) > 0.5
    pdbs = get_parallel_dbs(db)
    
    return db, pdbs
    
    